name: Release to Production

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0

jobs:
  build_and_deploy_android:
    name: Build & Deploy Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Decode Google Services JSON
        env:
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
        run: |
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > android/app/google-services.json
          
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEY_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Get Dependencies
        run: flutter pub get

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase appdistribution:distribute build/app/outputs/bundle/release/app-release.aab \
            --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} \
            --groups testers \
            --release-notes "New Release ${{ github.ref_name }}" \
            --token "$FIREBASE_TOKEN"

      - name: Upload to Play Console
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.yenyen0318.jpstudy
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: draft

      - name: Cleanup Keystore
        if: always()
        run: rm android/app/upload-keystore.jks android/key.properties
